version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pdf_content_db_root
      MYSQL_DATABASE: pdf_content_db
      MYSQL_USER: pdf_content_db_user
      MYSQL_PASSWORD: pdf_content_db_password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql-data:
